// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Restaurante.Infrastructure.Data;
using System;

namespace Restaurante.Infrastructure.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    partial class RestauranteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Restaurante.ApplicationCore.Entity.prato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("restaurante_id");

                    b.HasKey("id");

                    b.HasIndex("restaurante_id");

                    b.ToTable("prato");
                });

            modelBuilder.Entity("Restaurante.ApplicationCore.Entity.restaurante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("restaurante");
                });

            modelBuilder.Entity("Restaurante.ApplicationCore.Entity.prato", b =>
                {
                    b.HasOne("Restaurante.ApplicationCore.Entity.restaurante", "restaurante")
                        .WithMany("pratos")
                        .HasForeignKey("restaurante_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
